/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-03-23 18:29:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jspUseBean;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import bean.pojo.Ogrenci;

public final class ogrenciler_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("bean.pojo.Ogrenci");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Öğrenciler</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("ŞU ANDA ÖĞRENCİLER SAYFASINDAYIZ !!!!\r\n");
      out.write(" \r\n");
      out.write(" <br>\r\n");
      out.write(" ");
 Ogrenci o = (Ogrenci)request.getAttribute("ogrenci"); 
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.print(   "Adı Soyad : " + o.getAd() + " " + o.getSoyad()+ "<br>" );
      out.write(" \r\n");
      out.write(" ");
      out.print(   "Okul Numarası :" + o.getNo() + "<br>"  );
      out.write('\r');
      out.write('\n');
      out.write(' ');
      out.print(  " Sınıf / Şube :" + o.getSinif() + " /" +o.getSube() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1> ÖĞRENCİ 1 BİLGİLERİ </h1>\r\n");
      bean.pojo.Ogrenci ogrenci = null;
      ogrenci = (bean.pojo.Ogrenci) _jspx_page_context.getAttribute("ogrenci", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (ogrenci == null){
        ogrenci = new bean.pojo.DershaneOgrenci();
        _jspx_page_context.setAttribute("ogrenci", ogrenci, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci"), "no", "0000", null, null, false);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci"), "ad", "ADI_YOK", null, null, false);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci"), "soyad", "SOYADI_YOK", null, null, false);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci"), "sinif", "0", null, null, false);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci"), "sube", "X", null, null, false);
        out.write("\r\n");
        out.write("\r\n");
      }
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci"), "no", "7854", null, null, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci")).getNo())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci")).getAd())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci")).getSoyad())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci")).getSinif())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci")).getSube())));
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>ÖĞRENCİ 2 BİLGİLERİ </h1>\r\n");
      out.write("\r\n");
      bean.pojo.Ogrenci ogrenci2 = null;
      ogrenci2 = (bean.pojo.Ogrenci) _jspx_page_context.getAttribute("ogrenci2", jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (ogrenci2 == null){
        ogrenci2 = new bean.pojo.DershaneOgrenci();
        _jspx_page_context.setAttribute("ogrenci2", ogrenci2, jakarta.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write("\r\n");
        out.write("\r\n");
        out.write("  ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci2"), "no", "0000", null, null, false);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci2"), "ad", "ADI_YOK", null, null, false);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci2"), "soyad", "SOYADI_YOK", null, null, false);
        out.write("\r\n");
        out.write("  ");
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci2"), "sinif", "0", null, null, false);
        out.write('\r');
        out.write('\n');
        out.write(' ');
        org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("ogrenci2"), "sube", "X", null, null, false);
        out.write('\r');
        out.write('\n');
      }
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci2")).getNo())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci2")).getAd())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci2")).getSoyad())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci2")).getSinif())));
      out.write('\r');
      out.write('\n');
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((bean.pojo.DershaneOgrenci)_jspx_page_context.findAttribute("ogrenci2")).getSube())));
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body> \r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
